export const HELPER_LIST_REQUEST='PRODUCT_LIST_REQUEST'
export const HELPER_LIST_SUCCESS='PRODUCT_LIST_SUCCESS'
export const HELPER_LIST_FAIL='PRODUCT_LIST_FAIL'

export const HELPER_DETAILS_REQUEST='HELPER_DETAILS_REQUEST'
export const HELPER_DETAILS_SUCCESS='HELPER_DETAILS_SUCCESS'
export const HELPER_DETAILS_FAIL='HELPER_DETAILS_FAIL'

export const HELPER_DELETE_REQUEST='HELPER_DELETE_REQUEST'
export const HELPER_DELETE_SUCCESS='HELPER_DELETE_SUCCESS'
export const HELPER_DELETE_FAIL='HELPER_DELETE_FAIL'

export const HELPER_CREATE_REQUEST='HELPER_CREATE_REQUEST'
export const HELPER_CREATE_SUCCESS='HELPER_CREATE_SUCCESS'
export const HELPER_CREATE_FAIL='HELPER_CREATE_FAIL'
export const HELPER_CREATE_RESET='HELPER_CREATE_RESET'

export const HELPER_UPDATE_REQUEST='HELPER_UPDATE_REQUEST'
export const HELPER_UPDATE_SUCCESS='HELPER_UPDATE_SUCCESS'
export const HELPER_UPDATE_FAIL='HELPER_UPDATE_FAIL'
export const HELPER_UPDATE_RESET='HELPER_UPDATE_RESET'

export const HELPER_CREATE_REVIEW_REQUEST='HELPER_CREATE_REVIEW_REQUEST'
export const HELPER_CREATE_REVIEW_SUCCESS='HELPER_CREATE_REVIEW_SUCCESS'
export const HELPER_CREATE_REVIEW_FAIL='HELPER_CREATE_REVIEW_FAIL'
export const HELPER_CREATE_REVIEW_RESET='HELPER_CREATE_REVIEW_RESET'